const PENDING = "PENDING";
const ACCEPTED = "ACCEPTED";
const ASSIGNED = "ASSIGNED";
const QUOTED = "QUOTED";
const QUOTE_ACCEPTED = "QUOTE_ACCEPTED";
const ORDERED = "ORDERED";
const DISPATCHED = "DISPATCHED";
const REJECTED = "REJECTED";

export const STATUS_LIST = {
  PENDING,
  ACCEPTED,
  REJECTED,
  ASSIGNED,
  QUOTED,
  QUOTE_ACCEPTED,
  ORDERED,
  DISPATCHED,
};

export const ORGANIZATION_ID = "714361434540086498";
